In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
## Define the vocab size
vocab_size = 10000

In [4]:
##One hot representation for every word
one_hot_rep = [one_hot(words, vocab_size) for words in sentences]
one_hot_rep

[[3153, 416, 303, 6028],
 [3153, 416, 303, 6095],
 [3153, 3427, 303, 898],
 [3969, 4412, 4145, 5881, 5403],
 [3969, 4412, 4145, 5881, 6278],
 [975, 3153, 7261, 303, 4818],
 [2214, 2125, 8753, 5881]]

In [5]:
#Word Enbedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [9]:
sent_length = 8
embedded = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded)

[[   0    0    0    0 3153  416  303 6028]
 [   0    0    0    0 3153  416  303 6095]
 [   0    0    0    0 3153 3427  303  898]
 [   0    0    0 3969 4412 4145 5881 5403]
 [   0    0    0 3969 4412 4145 5881 6278]
 [   0    0    0  975 3153 7261  303 4818]
 [   0    0    0    0 2214 2125 8753 5881]]


In [11]:
##Feature Representation
dim = 10
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
model.predict(embedded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 944ms/step


array([[[-1.82160959e-02, -4.03697118e-02, -1.94902904e-02,
          3.79621647e-02,  4.96292226e-02, -1.77240260e-02,
          8.46577808e-03,  1.80276521e-02, -4.93880361e-03,
          3.02400030e-02],
        [-1.82160959e-02, -4.03697118e-02, -1.94902904e-02,
          3.79621647e-02,  4.96292226e-02, -1.77240260e-02,
          8.46577808e-03,  1.80276521e-02, -4.93880361e-03,
          3.02400030e-02],
        [-1.82160959e-02, -4.03697118e-02, -1.94902904e-02,
          3.79621647e-02,  4.96292226e-02, -1.77240260e-02,
          8.46577808e-03,  1.80276521e-02, -4.93880361e-03,
          3.02400030e-02],
        [-1.82160959e-02, -4.03697118e-02, -1.94902904e-02,
          3.79621647e-02,  4.96292226e-02, -1.77240260e-02,
          8.46577808e-03,  1.80276521e-02, -4.93880361e-03,
          3.02400030e-02],
        [-2.18210705e-02, -2.77222041e-02,  2.30415501e-02,
          4.80099656e-02,  2.49114968e-02, -4.57727686e-02,
         -4.40458320e-02,  4.03389968e-02, -2.010095