In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
sentences = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good developer',
    'understand the meaning of words',
    'your videos are good'
]

In [3]:
## Define the vocab size
vocab_size = 10000

In [4]:
##One hot representation for every word
one_hot_rep = [one_hot(words, vocab_size) for words in sentences]
one_hot_rep

[[3029, 4299, 579, 6442],
 [3029, 4299, 579, 8801],
 [3029, 9017, 579, 4417],
 [7277, 3806, 4277, 4465, 456],
 [7277, 3806, 4277, 4465, 4102],
 [9632, 3029, 1814, 579, 8550],
 [2181, 9987, 5740, 4465]]

In [5]:
#Word Enbedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [6]:
sent_length = 8
embedded = pad_sequences(one_hot_rep, padding='pre', maxlen=sent_length)
print(embedded)

[[   0    0    0    0 3029 4299  579 6442]
 [   0    0    0    0 3029 4299  579 8801]
 [   0    0    0    0 3029 9017  579 4417]
 [   0    0    0 7277 3806 4277 4465  456]
 [   0    0    0 7277 3806 4277 4465 4102]
 [   0    0    0 9632 3029 1814  579 8550]
 [   0    0    0    0 2181 9987 5740 4465]]


In [7]:
##Feature Representation
dim = 10
model = Sequential()
model.add(Embedding(vocab_size,dim,input_length=sent_length))
model.compile(optimizer='adam',loss='mse')

d:\jai\Python-Workspace\Krish Naik Udemy\Machine-Learning\12-Deep Learning\Bank_Employee_Retention_project\venv\Lib\site-packages\keras\src\layers\core\embedding.py:97: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [8]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [9]:
model.predict(embedded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 414ms/step


array([[[ 1.48313306e-02,  2.17721947e-02, -1.48617849e-02,
         -3.18062678e-02,  1.61133669e-02,  4.22205441e-02,
         -4.94721048e-02, -2.88070571e-02, -2.39335001e-04,
          4.52365726e-03],
        [ 1.48313306e-02,  2.17721947e-02, -1.48617849e-02,
         -3.18062678e-02,  1.61133669e-02,  4.22205441e-02,
         -4.94721048e-02, -2.88070571e-02, -2.39335001e-04,
          4.52365726e-03],
        [ 1.48313306e-02,  2.17721947e-02, -1.48617849e-02,
         -3.18062678e-02,  1.61133669e-02,  4.22205441e-02,
         -4.94721048e-02, -2.88070571e-02, -2.39335001e-04,
          4.52365726e-03],
        [ 1.48313306e-02,  2.17721947e-02, -1.48617849e-02,
         -3.18062678e-02,  1.61133669e-02,  4.22205441e-02,
         -4.94721048e-02, -2.88070571e-02, -2.39335001e-04,
          4.52365726e-03],
        [-1.24954060e-03,  2.09537409e-02, -4.68226075e-02,
          1.14733689e-02,  1.56719349e-02,  1.44617595e-02,
         -3.03159114e-02,  2.25926526e-02, -3.864370